package Continental.modelo;

public enum TipoEvento {
    COMENZOJUEGO, JUEGONOCOMENZADO, AGREGUEJUGADOR, PAUSAJUEGO, PREGUNTARROBARPOZO, REANUDARJUEGO, CAMBIOTURNO,
    HABILITARRONDA, FINRONDA, ULTIMARONDA,

}
