package Continental.modelo.eventos;

public enum TipoEvento {
    COMENZOJUEGO, JUEGONOCOMENZADO, JUGADORAGREGADO, PAUSAJUEGO, PREGUNTARROBARPOZO, REANUDARJUEGO, CAMBIOTURNO,
    HABILITARRONDA, FINRONDA, ULTIMARONDA, CARTAUBICADA, CARTADESCARTADA,

}
